# Generated by Django 5.0.2 on 2024-02-13 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zendesk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstoken",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
