# Generated by Django 5.0.2 on 2024-02-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zendesk", "0002_alter_accesstoken_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.IntegerField(unique=True)),
                ("assignee_id", models.IntegerField()),
                ("collaborator_ids", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField()),
                ("custom_fields", models.JSONField(default=dict)),
                ("custom_status_id", models.IntegerField()),
                ("description", models.TextField()),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("external_id", models.CharField(max_length=255)),
                ("follower_ids", models.JSONField(default=dict)),
                ("from_messaging_channel", models.BooleanField(default=False)),
                ("group_id", models.IntegerField()),
                ("has_incidents", models.BooleanField(default=False)),
                ("organization_id", models.IntegerField()),
                ("priority", models.CharField(max_length=50)),
                ("problem_id", models.IntegerField()),
                ("raw_subject", models.CharField(max_length=255)),
                ("recipient", models.EmailField(max_length=254)),
                ("requester_id", models.IntegerField()),
                ("satisfaction_rating", models.JSONField(default=dict)),
                ("sharing_agreement_ids", models.JSONField(default=dict)),
                ("status", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=255)),
                ("submitter_id", models.IntegerField()),
                ("tags", models.JSONField(default=dict)),
                ("type", models.CharField(max_length=50)),
                ("updated_at", models.DateTimeField()),
                ("url", models.URLField()),
                ("via", models.JSONField(default=dict)),
            ],
        ),
    ]
