# Generated by Django 5.0.2 on 2024-02-19 15:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zendesk", "0004_remove_ticket_assignee_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="assignee_email",
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="ticket",
            name="assignee_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="attribute_value_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="ticket",
            name="brand_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="collaborator_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="ticket",
            name="collaborators",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="ticket",
            name="comment",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="ticket",
            name="custom_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="ticket",
            name="custom_status_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="email_cc_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="ticket",
            name="email_ccs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="ticket",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="follower_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="ticket",
            name="followers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="ticket",
            name="group_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="organization_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="priority",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="problem_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="raw_subject",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="ticket",
            name="recipient",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="requester_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="safe_update",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="satisfaction_rating",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(default="new", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="subject",
            field=models.CharField(default="No Subject", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="submitter_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_form_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="updated_stamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="via",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="ticket",
            name="via_followup_source_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="via_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="voice_comment",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
