# Generated by Django 5.0.2 on 2024-02-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zendesk", "0006_alter_ticket_satisfaction_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="subdomain",
            field=models.CharField(default="default", max_length=50),
            preserve_default=False,
        ),
    ]
