# Generated by Django 5.0.2 on 2024-02-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zendesk", "0008_ticket_ticket_id_alter_ticket_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="last_fetch",
            field=models.DateTimeField(null=True),
        ),
    ]
