# Generated by Django 5.0.2 on 2024-03-04 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zendesk", "0009_accesstoken_last_fetch"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTicketCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subdomain", models.CharField(max_length=200)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("ticket_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("subdomain", "date")},
            },
        ),
    ]
