# Generated by Django 5.0.2 on 2024-03-04 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zendesk", "0011_alter_dailyticketcount_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyticketcount",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
